### ISSUE TITLE
音频输出问题

### ISSUE THREAD

**Issue by gangmain** [ShuyNiu/Dell-5060MFF-7060MFF-Hackintosh-EFI#1]
用耳机插入前面板耳机孔，看电影时变声，而且还有回声。直接用蓝牙耳机听没有问题。说明声卡已经没有问题，有线耳机输出不完美。

**Comment by ShuyNiu** [comment]
是的，在5060mff上耳机孔是可以正常使用的，7060mff有此问题。推测原因是使用耳机时音频输出由前面板的两个3.5mm接口共同输出，所以使用麦克风和耳机两个插头的耳机，或者使用二合一转接线可以解决。

有两种解决方法：
1. 在“系统偏好设置” - “声音” - “输出” 选择输出设备 “耳机”，将下方设置中的 “平衡” 拖动条从中间位置向左或者右拖动一些，为临时解决；
2. 使用“3.5mm母转双3.5mm公”音频二合一转接线。
[
](https://img14.360buyimg.com/n0/jfs/t1/80589/38/11349/240199/5d8b8249Ed6ac2c7e/caeb88a3f7587b75.jpg)

**Comment by TreyNiu** [comment]
将 boot-args 中的 alcid=3 条目删去即正常，已更新。

**Comment by gangmain** [comment]
如法炮制，问题解决。谢谢
