### ISSUE TITLE
DP直接输出没问题吧?

### ISSUE THREAD

**Issue by charliecaiyu** [ShuyNiu/Dell-5060MFF-7060MFF-Hackintosh-EFI#4]
RT

**Comment by TreyNiu** [comment]
没有DP接口的显示器，无法测试。
如果是DP转VGA，需要主动式转换器才能在macOS下使用，Windows无此问题。
如果是使用HDMI扩展板，可以直接使用。

**Comment by hdchieh** [comment]
> 没有DP接口的显示器，无法测试。 如果是DP转VGA，需要主动式转换器才能在macOS下使用，Windows无此问题。 如果是使用HDMI扩展板，可以直接使用。

没有问题
